package com.make_your_skill.ui.navigation

object AppRoutes {
    val MAIN_SCREEN = "main_screen"
    val PROFILE_SCREEN = "profile_screen"
    val SETTINGS_SCREEN = "settings_screen"
    val FIRST_SCREEN = "first_screen"
    val LOGIN_SCREEN = "login_screen"
    val REGISTER_SCREEN = "register_screen"
    val MATCH_SEARCH_SCREEN = "MatchSearchScreen"
    val PROFILE_MATCH_SCREEN = "ProfileMatchScreen"
    val PROFILE_SEARCH_SCREEN = "ProfileSearchScreen"
    val SEARCH_FOR_PAID_CLASSES_SCREEN = "SearchForPaidClassesScreen"
    val SKILL_SCREEN = "SkillScreen"
    val SKILL_SEARCH_SCREEN = "SkillSearchScreen"
    val INTERESTS_SCREEN = "interests_screen"
    val FIRST_NAME_SCREEN = "first_name_screen"
    val BIRTHDAY_SCREEN = "birthday_screen"
    val SKILLS_SCREEN = "skills_screen"
    val INTERESTED_SKILLS_SCREEN = "interestes_skills_screen"
    val RESULTS_SCREEN = "ResultsScreen"
    val ADD_SKILLS_INTEREST_SCREEN = "AddSkillsInterestsScreen"
    val CELL_PHONE_SCREEN = "cell_phone_screen"
    val MATCH_HISTORY_SCREEN = "match_history_screen"
    val CHANGE_PASSWORD_SCREEN = "change_password_screen"
}